#!/bin/bash -e

rm -f /var/log/dpkg.log
rm -f /var/log/apt/*
rm -f /var/cache/apt/*.bin
rm -f /var/cache/apt/archives/*.deb
rm -f /var/cache/apt/archives/partial/*.deb
rm -f /var/cache/debconf/*-old
rm -rf /var/lib/apt/lists/*
mkdir -p /var/lib/apt/lists/partial

find /usr/share/locale -mindepth 1 -maxdepth 1 \
    ! -name "en*" ! -name "locale.alias" | xargs rm -r || true

find /usr/share/doc -depth -type f ! -name copyright | xargs rm || true
find /usr/share/doc -empty | xargs rmdir || true

rm -rf /var/cache/man/*
rm -rf /usr/share/man/*
rm -rf /usr/share/info/*
rm -rf /usr/share/groff/*
rm -rf /usr/share/linda/*
rm -rf /usr/share/lintian/*

exit 0
