#!/bin/bash -e

usage() {
cat<<EOF
Syntax: $(basename $0) [ -options ]
Convenience script to clean APT cache and optionally package docs/locales

Options::

    -a --aggressive     delete package docs and locales

Environment::

    LANG                exclude from locales deletion (default: en_US)

EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        -a|--aggressive) aggressive="yes";;
        *)               usage;;
    esac
    shift
done

rm -f /var/log/apt/*
rm -f /var/log/dpkg.log
rm -f /var/cache/apt/*.bin
rm -f /var/cache/apt/archives/*.deb
rm -f /var/cache/apt/archives/partial/*.deb
rm -f /var/cache/debconf/*-old
rm -rf /var/lib/apt/lists/*
mkdir -p /var/lib/apt/lists/partial

if [ "$aggressive" == "yes" ]; then

    [ "$LANG" ] || LANG=en_US
    locale_excl=$(echo $LANG | cut -d_ -f1)

    find /usr/share/locale -mindepth 1 -maxdepth 1 \
        ! -name "${locale_excl}*" ! -name "locale.alias" | xargs rm -rf || true

    find /usr/share/doc -depth -type f ! -name copyright | xargs rm -f || true
    find /usr/share/doc -empty | xargs rm -rf || true

    rm -rf /var/cache/man/*
    rm -rf /usr/share/man/*
    rm -rf /usr/share/info/*
    rm -rf /usr/share/groff/*
    rm -rf /usr/share/linda/*
    rm -rf /usr/share/lintian/*
fi

exit 0
