#!/bin/bash -e

CODENAME=$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)

cat >/etc/apt/sources.list.d/sources.list<<EOF
deb http://httpredir.debian.org/debian $CODENAME main
# deb http://httpredir.debian.org/debian $CODENAME contrib
# deb http://httpredir.debian.org/debian $CODENAME non-free
EOF

cat >/etc/apt/sources.list.d/security.sources.list<<EOF
deb http://security.debian.org/ $CODENAME/updates main
# deb http://security.debian.org/ $CODENAME/updates contrib
# deb http://security.debian.org/ $CODENAME/updates non-free
EOF

# aggresively clean apt related files
/usr/local/sbin/apt-clean

