#!/bin/bash -e

export RELEASE=${RELEASE:-debian/jessie}

CODENAME=$(basename $RELEASE)
BASEDIR=/turnkey/tklx/base

docker run -it --rm --privileged \
    -e RELEASE \
    -e PKGCACHE=$BASEDIR/builder/chankos/$CODENAME/archives \
    -v $(dirname $(dirname $(realpath $0))):$BASEDIR \
    -w $BASEDIR \
    builder $@
