#!/bin/bash -e

# prevent initscript from running during install/update
echo "exit 101" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

dpkg-divert --local --rename --add /sbin/initctl
ln -sf /bin/true /sbin/initctl

# remove documentation (ref: overlay/etc/dpkg/dpkg.cfg.d/01_doc)
find /usr/share/doc -depth -type f ! -name copyright | xargs rm || true
find /usr/share/doc -empty | xargs rmdir || true
rm -rf /var/cache/man/*
rm -rf /usr/share/man/*
rm -rf /usr/share/info/*
rm -rf /usr/share/groff/*
rm -rf /usr/share/linda/*
rm -rf /usr/share/lintian/*

# remove locales (ref: overlay/etc/dpkg/dpkg.cfg.d/01_locale)
find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name 'en*' | xargs rm -r

